<?php

/**
 * BaseEpisodio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idEpisodio
 * @property string $nombre
 * @property string $fuentemp3
 * @property string $fuenteogg
 * @property integer $podcast_idPodcast
 * @property Podcast $Podcast
 * 
 * @method integer  getIdEpisodio()        Returns the current record's "idEpisodio" value
 * @method string   getNombre()            Returns the current record's "nombre" value
 * @method string   getFuentemp3()         Returns the current record's "fuentemp3" value
 * @method string   getFuenteogg()         Returns the current record's "fuenteogg" value
 * @method integer  getPodcastIdPodcast()  Returns the current record's "podcast_idPodcast" value
 * @method Podcast  getPodcast()           Returns the current record's "Podcast" value
 * @method Episodio setIdEpisodio()        Sets the current record's "idEpisodio" value
 * @method Episodio setNombre()            Sets the current record's "nombre" value
 * @method Episodio setFuentemp3()         Sets the current record's "fuentemp3" value
 * @method Episodio setFuenteogg()         Sets the current record's "fuenteogg" value
 * @method Episodio setPodcastIdPodcast()  Sets the current record's "podcast_idPodcast" value
 * @method Episodio setPodcast()           Sets the current record's "Podcast" value
 * 
 * @package    entrega3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEpisodio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('episodio');
        $this->hasColumn('idEpisodio', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('fuentemp3', 'string', 200, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 200,
             ));
        $this->hasColumn('fuenteogg', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
        $this->hasColumn('podcast_idPodcast', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Podcast', array(
             'local' => 'podcast_idPodcast',
             'foreign' => 'idPodcast'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}