<?php

/**
 * BaseCategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idCategoria
 * @property string $nombre
 * @property Doctrine_Collection $Podcast
 * 
 * @method integer             getIdCategoria() Returns the current record's "idCategoria" value
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method Doctrine_Collection getPodcast()     Returns the current record's "Podcast" collection
 * @method Categoria           setIdCategoria() Sets the current record's "idCategoria" value
 * @method Categoria           setNombre()      Sets the current record's "nombre" value
 * @method Categoria           setPodcast()     Sets the current record's "Podcast" collection
 * 
 * @package    entrega3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categoria');
        $this->hasColumn('idCategoria', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Podcast', array(
             'local' => 'idCategoria',
             'foreign' => 'categoria_idCategoria'));
    }
}