<?php

/**
 * PodcastTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PodcastTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PodcastTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Podcast');
    }
    
    public static function getPodcastPorId($id)
    {
    	$query = Doctrine_Query::create()
    	->select('p.*')
    	->from('podcast p')
    	->where('p.idpodcast = ?',$id);
    	return $query;
    }
     
    public static function getPodcastsHabilitados(){
    	$query = Doctrine_Query::create()
    	->select('p.*')
    	->from('podcast p')
    	->where('p.publicado = ?',1)
    	->orderBy('p.updated_at DESC');
    	return $query;
    }
    
    public static function getPodcastsPropiosYHabilitados()
    {
    	$user_id=sfContext::getInstance()->getUser()->getAttribute('user_id', null, 'sfGuardSecurityUser');
    	$subquery=  Doctrine_Query::create()
  					->select('ap.podcast_idpodcast')
  					->from('administradorpodcast ap')
  					->where('ap.user_id = ?', $user_id);
    	$sub= $subquery->execute();
    	$subquery= $sub->toArray();
    	$arr=array(999999999);
    	for($i=0;$i<(sizeof($subquery));$i++) $arr[$i]=$subquery[$i]['podcast_idpodcast'];
    	$query = Doctrine_Query::create()
  					->select('p.*')
  					->from('podcast p')
  					->where('p.user_id = ?', $user_id)
  					->orWhereIn('p.idpodcast', $arr);
    	return $query;
    }
    
    public static function getPodcastsTodos()
    {
    	$query = Doctrine_Query::create()
    	->select('p.*')
    	->from('podcast p');
    	return $query;
    }
    
    public static function getPodcastsLikeHabilitados($nombre){
    	$query = Doctrine_Query::create()
    	->from('podcast p')
    	->where('p.nombre LIKE ?','%'.$nombre.'%')
    	->andWhere('p.publicado = ?',1);
    	return $query;
    }
}