<?php

/**
 * ConfiguracionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConfiguracionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConfiguracionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Configuracion');
    }
    
    public static function getCantidadPodcastsPorPagina(){
    	$query = Doctrine_Query::create()
    	->select('c.cantidadpodcastporpagina')
    	->from('configuracion c');
    	return $query;
    }
    
    public static function getTitulo(){
    	$query = Doctrine_Query::create()
    	->select('c.nombresitio')
    	->from('configuracion c');
    	return $query;
    }
    
    public static function getSitioHabilitado(){
    	$query = Doctrine_Query::create()
    	->select('c.sitiohabilitado')
    	->from('configuracion c');
    	return $query;
    }
    
    public static function getEstilo(){
    	$query = Doctrine_Query::create()
    	->select('c.plantilladefecto')
    	->from('configuracion c');
    	return $query;
    }
    
    public static function getCantidadItemsPorPagina(){
    	$query = Doctrine_Query::create()
    	->select('c.cantidadItemsPorPagina')
    	->from('configuracion c');
    	return $query;
    }
}