<?php

/**
 * EpisodioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EpisodioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EpisodioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Episodio');
    }
    
    public static function getEpisodiosDePodcast($idpodcast)
    {
    	$query = Doctrine_Query::create()
    	->select('e.*')
    	->from('episodio e')
    	->where('e.podcast_idpodcast = ?', $idpodcast)
    	->orderBy('e.created_at DESC');
    	return $query;
    }
    
    public static function getEpisodiosPropiosYHabilitados()
    {
    	$subquery=PodcastTable::getPodcastsPropiosYHabilitados()->execute()->toArray();
    	$arr=array(99999999);
    	for($i=0;$i<(sizeof($subquery));$i++) $arr[$i]=$subquery[$i]['podcast_idpodcast'];
    	$query = Doctrine_Query::create()
    		->select('e.*')
    		->from('episodio e')
    		->whereIn('e.podcast_idpodcast', $arr);
    	return $query;   
    }
    
}