<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/26 18:24:16

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=podcast',
  'username' => 'root',
  'password' => 'alexhumar',
  'name' => 'doctrine',
)),);
