<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/01 20:11:15
sfConfig::add(array(
  'mod_administradorpodcast_enabled' => true,
  'mod_administradorpodcast_view_class' => 'sfPHP',
));
