<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/04/01 20:55:44
$this->security = array (
  'index' => 
  array (
    'is_secure' => true,
    'credentials' => 'administrador',
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
