<?php

/**
 * BaseAdministradorPodcast
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idPodcast
 * @property integer $podcast_idpodcast
 * @property integer $user_id
 * @property Podcast $Podcast
 * @property sfGuardUser $User
 * 
 * @method integer              getIdPodcast()         Returns the current record's "idPodcast" value
 * @method integer              getPodcastIdpodcast()  Returns the current record's "podcast_idpodcast" value
 * @method integer              getUserId()            Returns the current record's "user_id" value
 * @method Podcast              getPodcast()           Returns the current record's "Podcast" value
 * @method sfGuardUser          getUser()              Returns the current record's "User" value
 * @method AdministradorPodcast setIdPodcast()         Sets the current record's "idPodcast" value
 * @method AdministradorPodcast setPodcastIdpodcast()  Sets the current record's "podcast_idpodcast" value
 * @method AdministradorPodcast setUserId()            Sets the current record's "user_id" value
 * @method AdministradorPodcast setPodcast()           Sets the current record's "Podcast" value
 * @method AdministradorPodcast setUser()              Sets the current record's "User" value
 * 
 * @package    entrega3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdministradorPodcast extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('administradorpodcast');
        $this->hasColumn('idPodcast', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('podcast_idpodcast', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Podcast', array(
             'local' => 'podcast_idpodcast',
             'foreign' => 'idPodcast'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}