<?php

/**
 * BaseConfiguracion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idConfig
 * @property integer $cantidadItemsPorPagina
 * @property integer $cantidadPodcastPorPagina
 * @property string $plantillaDefecto
 * @property string $nombreSitio
 * @property boolean $sitioHabilitado
 * 
 * @method integer       getIdConfig()                 Returns the current record's "idConfig" value
 * @method integer       getCantidadItemsPorPagina()   Returns the current record's "cantidadItemsPorPagina" value
 * @method integer       getCantidadPodcastPorPagina() Returns the current record's "cantidadPodcastPorPagina" value
 * @method string        getPlantillaDefecto()         Returns the current record's "plantillaDefecto" value
 * @method string        getNombreSitio()              Returns the current record's "nombreSitio" value
 * @method boolean       getSitioHabilitado()          Returns the current record's "sitioHabilitado" value
 * @method Configuracion setIdConfig()                 Sets the current record's "idConfig" value
 * @method Configuracion setCantidadItemsPorPagina()   Sets the current record's "cantidadItemsPorPagina" value
 * @method Configuracion setCantidadPodcastPorPagina() Sets the current record's "cantidadPodcastPorPagina" value
 * @method Configuracion setPlantillaDefecto()         Sets the current record's "plantillaDefecto" value
 * @method Configuracion setNombreSitio()              Sets the current record's "nombreSitio" value
 * @method Configuracion setSitioHabilitado()          Sets the current record's "sitioHabilitado" value
 * 
 * @package    entrega3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConfiguracion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('configuracion');
        $this->hasColumn('idConfig', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('cantidadItemsPorPagina', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('cantidadPodcastPorPagina', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('plantillaDefecto', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('nombreSitio', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('sitioHabilitado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}